# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    # Runs a set of commands using the runners shell
    - name: Step that prints name of pull request's source branch
      run: |
        echo "Pull request's source branch is: ${HEAD_BRANCH}"
        echo "Value token is ${VALUE_TOKEN}"
      env:
        HEAD_BRANCH: ${{ github.head_ref }}
        VALUE_TOKEN: ${{ github.token }}
      if: github.event_name == 'pull_request'
    # Runs a set of commands using the runners shell
    - name: Step that prints name of pull request's source branch if hotfix
      run: |
        echo "Hotfix Pull request's source branch is: ${BASE_BRANCH}"
      env:
        BASE_BRANCH: ${{ github.head_ref }}
      if: contains(github.head_ref, 'hotfix')
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "develop"
